name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          IS_PRODUCTION: ${{ secrets.IS_PRODUCTION }}

      - name: Debug workspace
        run: |
          echo "Workspace contents:"
          ls -R
          echo "Output contents:"
          ls -R ./output

      - name: Test GITHUB_TOKEN permissions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b test-branch
          echo "Test file" > test.txt
          git add test.txt
          git commit -m "Test commit"
          git push origin test-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          force_orphan: true
          keep_files: false
