name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          mkdir -p ./logs
          npm run build > ./logs/build.log 2>&1 || echo "Build failed!"
          echo "Build logs:"
          cat ./logs/build.log
          
        env:
          API_URL: https://locflamedia.github.io/landing-page-v1
          API_KEY: https://locflamedia.github.io/landing-page-v1
          FRONTEND_URL: https://locflamedia.github.io/landing-page-v1
          IS_PRODUCTION: true

      - name: Create .nojekyll
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ladning-page-v1/dist
          force_orphan: true
          keep_files: false
